In [17]:
from math import ceil, floor
from random import shuffle

In [3]:
def troca(A, i, j):
    A[i], A[j] = A[j], A[i]

In [33]:
def quicksort(A):
    wall = 0
    pivot = A[-1]
    for i, a in enumerate(A):
        if a < pivot:
            troca(A, wall, i)
            wall += 1
            
    troca(A, wall, -1)
    left = A[:wall]
    if len(left) > 0:
        left = quicksort(left)
    right = A[(wall + 1):]
    if len(right) > 0:
        right = quicksort(right)
    return left + [pivot] + right

# I-ésimo valor, em média O(n)
Calculo de mediana

In [4]:
from random import choice
def particiona_aleatorio(A):
    x = choice(A)
    i = 0
    j = len(A)-1
    while True:
        while A[j] > x:
            j -= 1
        while A[i] < x:
            i += 1
        if i<j:
            troca(A,i,j)
        else:
            return j

In [145]:
def iesimo_media_linear(A, i):
    k = particiona_aleatorio(A)
    print(k)
    if i==k:
        return A[k]
    if i<k:
        return iesimo_media_linear(A[0:k], i)
    if i>k:
        return iesimo_media_linear(A[k+1:], i-k-1)

In [146]:
from random import shuffle
arr = [x*4 for x in range(1,51)]
median = arr[floor(len(arr)/2)]
shuffle(arr)
print(arr)
print("%d == %d?" % (median, iesimo_media_linear(arr, floor(len(arr)/2))))

[44, 104, 156, 196, 40, 184, 100, 52, 80, 164, 24, 48, 188, 112, 60, 8, 4, 152, 192, 96, 120, 168, 160, 172, 148, 200, 180, 20, 84, 76, 144, 88, 124, 128, 32, 176, 132, 12, 140, 36, 16, 108, 92, 116, 56, 64, 72, 136, 68, 28]
33
9
9
1
4
0
1
0
104 == 104


# I-ésimo valor em tempo linear O(n) mesmo no pior caso
Cálculo de mediana

In [44]:
# O ultimo elemento em A é utilizado como pivot
# O array no final fica:
    # A[0..q] elementos menores que o pivot
    # A[q] = pivot
    # A[q+1..len(A)] elementos maiores que o pivot
def particiona(A):
    x = A[-1]
    i = 0
    j = len(A)-1
    while True:
        while A[j] > x:
            j -= 1
        while A[i] < x:
            i += 1
        if i<j:
            troca(A,i,j)
        else:
            return j

In [41]:
# Forma simples de calcular a mediana, ordena e pega o elemento do meio.
# No algoritmo tem tempo constante pois todos os arrays aqui serão de tamanho <= 5
def mediana(A):
    #print("Mediana: %s" % str(A))
    aux = A[:]
    aux.sort() # Insertion sort, n importa muito
    med_inf = aux[floor(len(aux)/2)] # mediana inferior
    return med_inf

In [24]:
def busca(A, x): # indice do elemento x no vetor A[p..r]
    return A.index(x)

In [49]:
def select(A, i):
    if len(A)==1:
        return A[0]
    else:
        n = ceil(len(A)/5)
        B = []
        for j in range(0, n):
            B.append(mediana(A[5*j: min(5*(j + 1), len(A))])) # B com n <= 5 elementos
        
        x = select(B, ceil(n/2)-1) # recursivamente, obtem a mediana das medianas
        j = busca(A, x) # posição da mediana das medianas

        troca(A,j,len(A)-1) # coloca mediana das medianas no final, para ser utilizado de pivot no particiona
        q = particiona(A) # particiona A, em resumo, a esquerda ficam os elementos menores que A[r] e a direita os maiores
        
        if i==q: # verificamos se o pivot encontrado é o i-esimo que queriamos
            return x
        elif i < q:
            return select(A[:q], i)
        else:
            return select(A[q:], i-q)

In [54]:
# Criando um array de 25 elementos, 
ar = list(range(1,25+1))
ar = [x*4 for x in ar]
nesimo = floor(len(ar)/2)
med = ar[nesimo]
shuffle(ar)
print(ar)
print("Mediana = %dsimo elemento = %d" % (nesimo+1, med))
print("Resultado: %d " % select(ar, nesimo))

[68, 52, 12, 76, 84, 44, 60, 64, 80, 48, 88, 96, 40, 92, 24, 56, 100, 28, 4, 32, 20, 72, 8, 16, 36]
Mediana = 13simo elemento = 52
Resultado: 52 


# RadixSort

In [159]:
# Considere esse counting sort, recebe o array, o valor maximo, e a funcao indice
def counting_sort(A, max_value, get_index):
    counts = [0] * max_value
    # Counting - O(n)
    for a in A:
        counts[get_index(a)] += 1
        
    # Accumulating - O(k)
    for i, c in enumerate(counts):
        if i == 0:
            continue
        else:
            counts[i] += counts[i-1]

    # Calculating start index - O(k)
    for i, c in enumerate(counts[:-1]):
        if i == 0:
            counts[i] = 0
        counts[i+1] = c

    ret = [None] * len(arr)
    # Sorting - O(n)
    for a in A:
        index = counts[get_index(a)]
        ret[index] = a
        counts[get_index(a)] += 1
    return [x for x in ret if x is not None]

In [160]:
counting_sort([1,0,1,3,2,6,4,5],7,lambda x:x)

[0, 1, 1, 2, 3, 4, 5, 6]

In [29]:
# Default: Base decimal
def get_digit(n, d, base):
    for i in range(d-1):
        n //= base
    return n % base

def get_num_difit(n, base):
    i = 0
    while n > 0:
        n //= base
        i += 1
    return i

def radix_sort(A, max_value, base=10): #
    num_digits = get_num_difit(max_value, base)
    print(num_digits)
    # O(k(n+k))
    for d in range(num_digits):
        # Counting sort takes O(n+k)
        arr = counting_sort(A, max_value, lambda a: get_digit(a, d+1, base))
    return arr

In [28]:
def bucket_sort(A, max_value, n_buckets, get_index, bucket_sorting_function):
    buckets = [[]] * n_buckets
    
    for a in A:
        buckets[get_index(a)].append(a)
    for index, bucket in enumerate(buckets):
        #Using the other sort to sort individual buckets
        buckets[index] = bucket_sorting_function(bucket)
        
    return [a for a in bucket for bucket in buckets]

# HeapSort

In [38]:

# Python program for implementation of heap Sort 
  
# To heapify subtree rooted at index i. 
# n is size of heap 
def max_heapify(A, n, i): 
    largest = i # Initialize largest as root 
    l = 2 * i + 1     # left = 2*i + 1 
    r = 2 * i + 2     # right = 2*i + 2 
  
    # See if left child of root exists and is 
    # greater than root 
    if l < n and arr[i] < arr[l]: 
        largest = l 
  
    # See if right child of root exists and is 
    # greater than root 
    if r < n and arr[largest] < arr[r]: 
        largest = r 
  
    # Change root, if needed 
    if largest != i: 
        arr[i],arr[largest] = arr[largest],arr[i] # swap 

        # Heapify the root. 
        max_heapify(arr, n, largest) 
        
# The main function to sort an array of given size 
def heap_sort(A): 
    n = len(A) 
  
    # Build a maxheap. 
    for i in range(n, -1, -1): 
        max_heapify(A, n, i) 
  
    # One by one extract elements 
    for i in range(n-1, 0, -1): 
        arr[i], arr[0] = arr[0], arr[i] # swap 
        max_heapify(A, i, 0) 
        
# Driver code to test above 
arr = [ 12, 11, 13, 5, 6, 7] 
heap_sort(arr) 
print(arr)

[5, 6, 7, 11, 12, 13]


# MergeSort

In [149]:
def merge(llist, rlist):
    final = []
    while llist or rlist:
        if len(llist) and len(rlist):
            if llist[0] < rlist[0]:
                final.append(llist.pop(0))
            else:
                final.append(rlist.pop(0))
                
        if not len(llist):
            if len(rlist): 
                final.append(rlist.pop(0))
        if not len(rlist):
            if len(llist): 
                final.append(llist.pop(0))
    return final
 
def merge_sort(A):
    if len(A) < 2: 
        return A
    mid = floor(len(A) / 2)
    return merge(merge_sort(A[:mid]), merge_sort(A[mid:]))

In [150]:
merge_sort([0,123,123,123,12,31,51,243,124,123])

[0, 12, 31, 51, 123, 123, 123, 123, 124, 243]

# Mochila

In [35]:
def mochila01(V,W,k):
    n = len(V)
    c = [([0]*220)]*k
    for i in range(1,n):
        for j in range(0, k+1):
            if j>=W[i]:
                c[i][j] = max(V[i]+c[i-1][j-W[i]], c[i-1][j])
            else:
                c[i][j] = c[i-1][j]
    return c[n][k]

mochila01([60,100,120],[10,20,30],50)

220


# Minimo operações na multiplicação de matrizes

## Solução Recursiva

In [67]:
ROW = 0
COL = 1
def n_operacoes_m(a,b):
    return a[ROW] * a[COL] * b[COL]

# Isso aqui simplesmente te devolve o tamanho da matriz resultante da multiplicação.
# Ex: A(2,3) * B(3,4) * C(4,5) isso irá retornar (2,5)
def tamanho_m_cadeia(p): 
    return p[0][ROW],p[-1][COL]

def min_op_multiplicacao(p):
    if len(p) == 1:
        return 0  # Caso base
    return min(
        min_op_multiplicacao(p[1:]) + n_operacoes_m(p[0], tamanho_m_cadeia(p[1:])),
        min_op_multiplicacao(p[:-1]) + n_operacoes_m(tamanho_m_cadeia(p[:-1]), p[-1])
    )
min_op_multiplicacao(p=[(10,20),(20,50),(50,1),(1,100)])

2200

Problema? repete a mesma operação várias vezes, cada vez que você chama o minMult recursivamente acaba calculando de novo. O negócio é colocar tudo numa tabela boladona.

## Solução com programação dinâmica

In [106]:
def n_operacoes_m(a,b):
    return a[ROW] * a[COL] * b[COL]

def tamanho_m_cadeia(p):
    return p[0][ROW],p[-1][COL]

def min_op_multiplicacao(p):
    n = len(p)
    memo = np.full((n,n), -1) # -1 só para indicar que não foi inicializado, já que vamos colocar uns zeros por ai
    
    for i in range(0, n):
        memo[i][i] = 0
        
    for j in range(1,n): # coluna por coluna
        # vamos percorrer a nossa coluna inteira, partindo do maior indice da linha para o menor (de baixo para cima na tabela)
        for i in range(0,j)[::-1]: 
            memo[i][j] = min(
                memo[i][j-1] + n_operacoes_m(tamanho_m_cadeia(p[i:j]), p[j]), # esquerda
                memo[i+1][j] + n_operacoes_m(p[i], tamanho_m_cadeia(p[i+1:j+1])) # baixo
            )

    print(memo)
    return memo[0][-1] # último elemento da primeira linha
min_op_multiplicacao(p=[(10,20),(20,50),(50,1),(1,100)])

[[    0 10000  1200  2200]
 [   -1     0  1000  3000]
 [   -1    -1     0  5000]
 [   -1    -1    -1     0]]


2200